# Generated by Django 3.2.6 on 2021-08-11 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_group', models.CharField(max_length=50)),
                ('members', models.ManyToManyField(blank=True, related_name='access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
