# Generated by Django 3.2.6 on 2021-08-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name_of_group',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
